### ISSUE TITLE
One of my medusa avatars won't respond to the code, but it's siblings will.

### ISSUE THREAD

**Issue by Miilkytea** [Miilkytea/awesome5000#1]
What User Story (or feature) are you working on?
The user Medusa (the blue one at the bottom of the page) picks one of the three other Gorgons, and when they are 'out', they turn to stone and fade away. The purple Gorgon at the top of the page is supposed to turn to stone and fade away like the others but is not responding to the code. 

What error are you getting?
I am getting ZERO errors. There are no spelling mistakes or mislabeled tags. It's simply not working even though its siblings have the same exact code and work. I'm completely stumped. I've checked everything in the console and there are no spelling/syntax mistakes or errors.

How have you attempted to fix your error?
I have scanned every line to make sure everything looks in order. Went back over the logic of the function to make sure it's working correctly. I've moved around classes. The logic is sound but -
  if (threeSelectionObj.out === true) {
    $("#three").removeClass("threeLoad").addClass("stoneThree");
    $("#three").fadeOut(3000);

is not removing the threeLoad class and then adding the stoneThree class even though it's no different from the other elements that are responding to the same exact code. Stumped.
-Thanks!

**Comment by ghost** [comment]
First, please check out my comment to Kevin in kjh311/Game_of_Thrones_Concentration_Game#1.

Nice issue, come talk to me if you need help. Closes #1.
